name: Lint and Auto-Fix

on:
  push:
    branches:
      - main

jobs:
  lint-and-fix:
    name: Lint & Auto-Fix Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Lint & fix JavaScript (Standard)
        run: |
          npx standard --fix "js/**/*.js"

      - name: Lint HTML (htmlhint)
        run: npx htmlhint "**/*.html" --config .htmlhintrc

      - name: Lint & fix CSS (stylelint)
        run: npx stylelint "**/*.css" --fix

      - name: Commit & push any fixes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore: auto-fix lint issues [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
